{% set name = "PcapPlusPlus" %}
{% set version = "24.09" %}

package:
  name: lib{{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/seladb/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: def261fd9c64455d5f793e1e859108f706d5a6917e7aeb31dc8828543e00bc63

build:
  number: 0
  skip: true  # [win]

outputs:
  - name: libpcapplusplus
    build:
      run_exports:
        - {{ pin_subpackage( 'pcapplusplus-licenses', max_pin='x.x') }}
    script: build-lib.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - make
      host:
        - libpcap
    test:
      commands:
        - test -f ${PREFIX}/include/pcapplusplus/PcapPlusPlusVersion.h
        - test -f ${PREFIX}/lib/libCommon++.a
        - test -f ${PREFIX}/lib/libPacket++.a
        - test -f ${PREFIX}/lib/libPcap++.a
  - name: pcapplusplus-licenses
    build:
      noarch: generic

about:
  home: https://pcapplusplus.github.io/
  license: Unlicense AND MIT AND Zlib AND BSD-2-Clause AND ZPL-2.1
  license_file:
    - LICENSE
    - 3rdParty/LightPcapNg/LightPcapNg/LICENSE.txt
    - 3rdParty/MemPlumber/MemPlumber/LICENSE
    - 3rdParty/dirent-for-Visual-Studio/LICENSE
    - 3rdParty/hash-library/LICENSE
    - 3rdParty/Getopt-for-Visual-Studio/getopt.h
    - 3rdParty/EndianPortable/include/EndianPortable.h
  summary: PcapPlusPlus is a multiplatform C++ library for capturing, parsing and crafting of network packets
  doc_url: https://pcapplusplus.github.io/docs/quickstart
  dev_url: https://github.com/seladb/PcapPlusPlus

extra:
  recipe-maintainers:
    - asafkahlon
